# Generated by Django 6.0.7 on 2026-07-18 15:37

import clipboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=clipboard.models.generate_short_id, max_length=10, unique=True)),
                ('content', models.TextField()),
                ('format_type', models.CharField(choices=[('text', '纯文本'), ('markdown', 'Markdown')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clipboard_data',
            },
        ),
    ]
