# Generated by Django 6.0.7 on 2026-07-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_comment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='clipboard_c_content_7aa003_idx',
            old_name='clipboard_c_content_9451d8_idx',
        ),
    ]
