# Generated by Django 6.0.7 on 2026-07-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clipboard", "0003_rename_clipboard_c_content_9451d8_idx_clipboard_c_content_7aa003_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="object_pk",
            new_name="object_id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
